export const SKILL_KEYWORDS: Record<string, string[]> = {
  accessibility: ["accessibility", "a11y", "wcag", "screen reader"],
  airflow: ["airflow", "apache airflow"],
  ansible: ["ansible"],
  aws: ["aws", "amazon web services", "ec2", "lambda", "s3", "cloudformation"],
  azure: ["azure", "microsoft azure", "azure functions", "azure devops"],
  bash: ["bash", "shell scripting", "shell script", "zsh"],
  "ci/cd": ["ci/cd", "ci cd", "github actions", "gitlab ci", "jenkins"],
  "cloud security": ["cloud security", "security groups", "waf", "guardduty"],
  css: ["css", "tailwind", "tailwindcss", "sass", "scss", "styled-components"],
  databricks: ["databricks"],
  dbt: ["dbt", "data build tool"],
  docker: ["docker", "containerization", "containers"],
  etl: ["etl", "data pipeline", "data pipelines", "data ingestion"],
  firebase: ["firebase", "firestore", "firebase auth"],
  flutter: ["flutter", "dart"],
  gcp: ["gcp", "google cloud", "bigquery", "cloud run", "gke"],
  git: ["git", "github", "gitlab", "bitbucket"],
  go: ["golang", "go language", "go"],
  graphql: ["graphql", "apollo"],
  helm: ["helm", "helm charts"],
  html: ["html", "html5"],
  iam: ["iam", "identity and access management", "access control", "rbac"],
  "incident response": ["incident response", "on-call", "postmortem", "root cause analysis"],
  javascript: ["javascript", "js", "es6", "ecmascript"],
  java: ["java", "spring boot", "spring"],
  jupyter: ["jupyter", "jupyter notebook", "notebook"],
  kafka: ["kafka", "apache kafka", "event streaming"],
  kotlin: ["kotlin", "android development"],
  kubernetes: ["kubernetes", "k8s", "helm"],
  linux: ["linux", "bash", "shell scripting", "unix"],
  mlops: ["mlops", "model deployment", "model serving", "feature store"],
  "mobile ui": [
    "mobile ui",
    "ios ui",
    "android ui",
    "material design",
    "swiftui",
    "jetpack compose",
  ],
  microservices: ["microservices", "service-oriented architecture", "distributed systems"],
  monitoring: ["monitoring", "observability", "prometheus", "grafana", "datadog", "new relic"],
  mongodb: ["mongodb", "mongo"],
  networking: ["networking", "tcp/ip", "dns", "http", "load balancer", "vpc"],
  "next.js": ["next.js", "nextjs"],
  "node.js": ["node", "node.js", "nodejs", "express", "nestjs"],
  numpy: ["numpy"],
  pandas: ["pandas"],
  postgresql: ["postgres", "postgresql"],
  python: ["python", "pandas", "numpy", "fastapi", "django", "flask"],
  pytorch: ["pytorch", "torch"],
  react: ["react", "next.js", "nextjs", "redux"],
  "react native": ["react native", "expo"],
  redis: ["redis"],
  "rest api": ["rest api", "restful api", "api development", "http api"],
  redux: ["redux", "redux toolkit"],
  "scikit-learn": ["scikit-learn", "sklearn"],
  siem: [
    "siem",
    "splunk",
    "elk",
    "elastic stack",
    "security information and event management",
  ],
  spark: ["spark", "apache spark", "pyspark"],
  sql: ["sql", "postgres", "postgresql", "mysql", "sqlite", "snowflake"],
  snowflake: ["snowflake"],
  swift: ["swift", "swiftui", "ios development"],
  "tailwind css": ["tailwind", "tailwindcss"],
  tensorflow: ["tensorflow", "keras"],
  testing: ["testing", "unit test", "integration test", "jest", "vitest", "cypress", "playwright"],
  terraform: ["terraform", "iac", "infrastructure as code"],
  typescript: ["typescript", "ts"],
};

export const KNOWN_SKILLS = Object.keys(SKILL_KEYWORDS).sort();
